client_config_backend: settings
client_config:
  client_id: 278510939115-av8v0be8u58h6dhjmf8s0gvdt6t1uc5a.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install